### ISSUE TITLE
Howto build on Linux?

### ISSUE THREAD

**Issue by hansbogert** [xCuri0/ReBarUEFI#2]
I did the following:

```shell
git clone https://github.com/tianocore/edk2.git
cd edk2
git clone https://github.com/xCuri0/ReBarUEFI.git
cd ReBarUEFI/ReBarDxe
python3 buildffs.py

Traceback (most recent call last):
  File "/home/gandalf/src/edk2/ReBarUEFI/ReBarDxe/buildffs.py", line 18, in <module>
    subprocess.run(["build", "--platform=ReBarUEFI/ReBarDxe/ReBar.dsc"], shell=shell, env=os.environ, stderr=sys.stderr, stdout=sys.stdout)
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'build'

```

**Comment by xCuri0** [comment]
You need to setup edk2 environment before building

[https://github.com/tianocore/tianocore.github.io/wiki/Common-instructions](https://github.com/tianocore/tianocore.github.io/wiki/Common-instructions)

**Comment by hansbogert** [comment]
@xCuri0 never thanked you, hereby, thanks!
